### ISSUE TITLE
On Home Page Back button Issue

### ISSUE THREAD

**Issue by pawankhandal52** [UdacityAndroidDevScholarship/gis-2k18#25]
This issue on a this branch "Firebase-Added"
When user select the Navigation Drawer item one by one Like Members after that GIS Stories.
then the issue is when pressing the device back button then it will show all the pages on by one.

Solution:- When user click back button then simply close the application.

**Comment by knightcube** [comment]
do you want to work on this issue and fix it?

**Comment by pawankhandal52** [comment]
Yes i Want to work on this issue and fix this asap.

**Comment by knightcube** [comment]
i am sorry i will assign it to you after some time

**Comment by pawankhandal52** [comment]
So can i start work on that or wait for your time  when you will assign.

**Comment by knightcube** [comment]
i have assigned this issue to you....you can start working on it right away

**Comment by sidhuparas** [comment]
Pressing the back button and closing the app sometimes make a horrible experience. I have faced this once. 

Alternative: Instead we can just show the Navigation Drawer when back button is clicked and if it’s clicked again within 2 seconds, close the app. This behavior is also implemented in some apps.

I think mods need to think on it @knightcube

**Comment by pawankhandal52** [comment]
@knightcube I have fix the issue now when user is press the back button then App will close.

**Comment by Saurav2304** [comment]
Yes.. Send pull request!
