### ISSUE TITLE
PROFILE UI MOCKUP SECTION

### ISSUE THREAD

**Issue by TheRaider** [UdacityAndroidDevScholarship/gis-2k18#37]
**Profile Activity**
  _--> This activity has all the info related to the community member and also his work done outside and inside Google India Scholarship programme_

This activity will consist of mainly **_3 tabs_** namely : 
**1. About** 
   It consists of all the details of the community member like a short description, emails, GitHub links and other social media links, Skills, Address and all other basic info
**2. GIS**
 This contains all the stories, posts, challenges, projects the community member has done in Google India Scholarship  in phase 1 and phase 2
**3. Projects**
 It contains all the projects of the community member outside Google India Scholarship Programme

**Sample UI :**

**_1. Profile About UI_**
<img src="https://user-images.githubusercontent.com/21246791/39249587-99d9f73c-48bc-11e8-93db-1874ae0dcaf4.png" alt="profile about" height="400px">

**_2. Profile GIS UI_**
<img src="https://user-images.githubusercontent.com/21246791/39249590-9a4c710e-48bc-11e8-9755-cd1688ba9e2e.png" alt="profile gis" height="400px">

**_3. Profile Projects UI_**
<img src="https://user-images.githubusercontent.com/21246791/39249593-9aa8a212-48bc-11e8-893e-9c70f640255c.png" alt="profile projects" height="400px">

**_You can share and submit all your mocks ups related to Profile UI here_**
**Our main aim is to create a User-friendly UI**

We are open to suggestions for improvement and even better UI mockup

P.S: Please resize the image if it's too big.

**Comment by tavishjain** [comment]
@TheRaider from where should the functionality to acces the profile be added? The nav bar or toolbar ??

**Comment by TheRaider** [comment]
@tavishjain It will be neither in Navigation drawer or Toolbar. The Profile UI activity is the activity that is displayed when you click on a member in the Members Fragment of the app.

**Comment by GauravR31** [comment]
Can I work on this?

**Comment by TheRaider** [comment]
I have already coded the layouts and I am adding functionality to it. I will submit as the PR as soon as possible.
