### ISSUE TITLE
Add Login Screen

### ISSUE THREAD

**Issue by knightcube** [UdacityAndroidDevScholarship/gis-2k18#4]
Will make the Login Screen layout. Functionality can be added later on when Firebase is setup properly with details.

This is the basic design for our GIS app login screen the starter code is available.
Its Time the to show your programming skills and submit pull request for this **LOGIN feature**

**We open for suggestion for improvement and even better UI mockup** 

![login](https://user-images.githubusercontent.com/24786147/38937725-77f20950-4341-11e8-8612-ace1960fdedc.jpeg)
P.S: Please resize the image if it's too big.
[Click here to know how to do it.](https://github.com/UdacityAndroidDevScholarship/gis-2k18/wiki/Usefull-markdown-things-will-posting-issues-and-PRs)

**Comment by surya07081995** [comment]
#6 
Hi there, This mockup Login UI is made by me.
I'm posting the modified of it.
Do consider the UI design if it looks good to you.
![component](https://user-images.githubusercontent.com/20954321/38689911-6ec2269a-3e9a-11e8-9370-44584ab74999.png)

**Comment by amarjeetkapoor1** [comment]
Hi, guys try to use small pics or resize

By replacing the link that github provide with something like below.

```
![image](https://yourImageURL) 

<img src="https://yourImageURL" width="xwith" height="yheight">
```
 for uploading here or just upload the pic at https://imgur.com/ by clicking on a new post ( no need to create a profile) and sharing the link of the image here.

**Comment by surya07081995** [comment]
Hi @knightcube, may I know the selection procedure of Login UI.
Thanks!

**Comment by sidhuparas** [comment]
Hey guys, are you accepting the mockups?

Here's mine for some other app: 

<img src="https://user-images.githubusercontent.com/26019488/38799231-85cdba9a-4181-11e8-9114-491cab9f809f.png" width=400/>

I can modify it according to our needs if required.

**Comment by AjaySharvesh3** [comment]
Shall I claim this issue?? @knightcube

**Comment by Devesh1396** [comment]
Here is my login screen!
![login_mockup](https://user-images.githubusercontent.com/38135562/38989457-a4a91408-43f4-11e8-8e7f-28e127214cdc.png)
