### ISSUE TITLE
User Details Activity

### ISSUE THREAD

**Issue by TheRaider** [UdacityAndroidDevScholarship/gis-2k18#56]
There are 2 types of users for the app : 
1.**Authenticated User:** Any recipient of Google India Scholarships is an Authenticated user. They can sign into the app using their username and the password with which they have registered.  
2. **Guest User:**  The ones who are not recipients of Google India Scholarship are guest users. They need not sign in but they can view the app.

**Authenticated User vs Guest User:** 
An authenticated user can edit his profile, projects, challenges and all the data he has submitted at the first time login of the app.
 A Guest User has all the benefits of an authenticated user except one thing. A guest user will not be able to add any details about him/her because he is not a GIS recipient thereby he cannot edit any details too.

## The Issue is to create a User Details activity in which an authenticated can add all his details and can also edit them

> It will be same as that of profile activity in members section except In members section, you can only view details of all the members but  in User details activity , you can edit the details of the member who has logged in

 **In User details activity** 
> 1. User can add/edit profile picture
> 2. User can add/edit one line description
> 3. User can add/edit short description
> 4. User can add/edit skills
> 5. User can add/edit GIS stories
> 6. User can add/edit GIS projects
> 7. User can add/edit GIS challenges
> 8. User can add/edit own projects out of GIS
> 9. User can upload profile pic from gallery or camera
> 10. User can upload projects' image from gallery or camera
> 11. User can upload stories' image from gallery or camera

### **In one line the User details Activity is Profile Activity with every part having editing and saving functionality**

You can design the way you want. But see the below screenshots of profile activity and use them as reference

**_1. Profile About UI_**
<img src="https://user-images.githubusercontent.com/21246791/39249587-99d9f73c-48bc-11e8-93db-1874ae0dcaf4.png" alt="profile about" height="400px">

**_2. Profile GIS UI_**
<img src="https://user-images.githubusercontent.com/21246791/39249590-9a4c710e-48bc-11e8-9755-cd1688ba9e2e.png" alt="profile gis" height="400px">

**_3. Profile Projects UI_**
<img src="https://user-images.githubusercontent.com/21246791/39249593-9aa8a212-48bc-11e8-893e-9c70f640255c.png" alt="profile projects" height="400px">

**Comment by sud8443** [comment]
I would like to work on this issue

**Comment by xsahil03x** [comment]
Can i work on this ?

**Comment by Sudhanshu96** [comment]
@xsahil03x I have already started working on this issue and I have covered a lot. So you can take up another issue.

**Comment by sud8443** [comment]
@xsahil03x I have already started working on this issue and I have covered a lot. So you can take up another issue.

**Comment by derrickabreo** [comment]
@xsahil03x I think you can work on this issue as the mods will select the best PR.
