### ISSUE TITLE
Replace png icons with  xxhdpi, xhdpi, hdpi, mdpi and ldpi drawables in the project

### ISSUE THREAD

**Issue by knightcube** [UdacityAndroidDevScholarship/gis-2k18#58]
There are several icons that are in png format in the project. It should be replaced with proper sized drawables. You can take help from here to do so - https://medium.com/code-yoga/create-drawables-from-a-large-scale-image-automatically-2128dde61ad9

**Comment by RajaParikshit** [comment]
Thank you so much !!!

**Comment by sud8443** [comment]
@knightcube can you just list the replacements. It will be easier in this way.

**Comment by knightcube** [comment]
replace *all* the png images with drawables

**Comment by intkhabahmed** [comment]
@knightcube I will recommend to create only xxxhdpi, xxhdpi and mdpi and ignore xhdpi, hdpi, ldpi. It will save memory. See this video
https://www.youtube.com/watch?v=u5xP4tFQlkA&t=142s
