### ISSUE TITLE
Challenges UI MOCK UP Section

### ISSUE THREAD

**Issue by Rahulxx01** [UdacityAndroidDevScholarship/gis-2k18#6]
**Challenge Section Activity**

This activity will **SHOWCASE** the best results from challenges proposed by the moderator of channel showcase 
For eg : Best results from Copy layout challenge and Layout challenge will be displayed here.

This issue is made so that everyone can **share** and **submit** their **UI Mock Ups**.

**Our main aim to get a user-friendly UI for this activity**
  
P.S: Please resize the image if it's too big.
[Click here to know how to do it.](https://github.com/UdacityAndroidDevScholarship/gis-2k18/wiki/Usefull-markdown-things-will-posting-issues-and-PRs)
**We open for suggestion for improvement and even better UI mockup**

**Comment by abanidas** [comment]
Hi Mods, here is the UI Mock Up for the **Showcase Layout** that I have designed. 
Please consider it if it looks good.

<img src="https://user-images.githubusercontent.com/18400670/38713561-5c3f8562-3eef-11e8-813b-679970085a3a.PNG" width="170" height="340"/>

**Comment by Saurav2304** [comment]
@abanidas Kindly PR the xml file for the UI!

**Comment by abanidas** [comment]
@Saurav2304 sure, it was a mock up. I will implement it and will create a PR.
