### ISSUE TITLE
Please use proper coding conventions

### ISSUE THREAD

**Issue by knightcube** [UdacityAndroidDevScholarship/gis-2k18#62]
There are currently alot of places in the project where conventions have not been followed. Please follow the conventions that are provided here - https://blog.mindorks.com/android-code-style-and-guidelines-d5f80453d5c7 . It becomes easy to solve bugs if the conventions are followed. Anyone willing to beautify the codes using proper conventions given in the link?

**Comment by gaurav-bharti** [comment]
I'm on it.
