### ISSUE TITLE
Spinner's UI is not consistent with the rest of the UI

### ISSUE THREAD

**Issue by sud8443** [UdacityAndroidDevScholarship/gis-2k18#64]
The spinner's UI is not consistent with the rest of the UI. The default dropdown resource is used so I suggest that we should customize the spinner and make it's UI consistent according to the rest of the color scheme.
![spinner s ui not consistent](https://user-images.githubusercontent.com/19422016/39482749-dbd573de-4d8d-11e8-8f6b-2fed700b2f92.png)

**Comment by sud8443** [comment]
I would like to work on this.

**Comment by knightcube** [comment]
sure.....you can work on this....send a PR with a screenshot and we will take a look

**Comment by sud8443** [comment]
@knightcube already did that. You can review that

**Comment by knightcube** [comment]
done
