### ISSUE TITLE
Git Conflict Symbols in Strings.xml

### ISSUE THREAD

**Issue by derrickabreo** [UdacityAndroidDevScholarship/gis-2k18#66]
There are git Conflict symbols in strings.xml file at line 44 and line 142.

**Comment by amarjeetkapoor1** [comment]
Caused by : https://github.com/UdacityAndroidDevScholarship/gis-2k18/commit/af10a59ce0d9449f85973e395544c07bc6d5c44f

**Comment by derrickabreo** [comment]
@amarjeetkapoor1 Please Review the PR.
