### ISSUE TITLE
GIS Stories Mock Up Section

### ISSUE THREAD

**Issue by Rahulxx01** [UdacityAndroidDevScholarship/gis-2k18#7]
**GIS Stories activity.**

This activity will display the Stories of all participants who wish to share their experience from this program.

**Best stories** will be featured on the **Top** so that many people get inspired by the scholarship program.

In this issue you can **share** and **submit** all the **UI designs** for this functionality.

_**Our aim is to get user-friendly UI**_ 

For eg:
![gis stories](https://user-images.githubusercontent.com/24786147/38680117-22eec6ae-3e83-11e8-87a5-186a0e81d2a9.png)

**We open for suggestion for improvement and even better UI mockup** 
P.S: Please resize the image if it's too big.
[Click here to know how to do it.](https://github.com/UdacityAndroidDevScholarship/gis-2k18/wiki/Usefull-markdown-things-will-posting-issues-and-PRs)

**Comment by nishank95** [comment]
I can work on this UI. I had a doubt is this the final layout for stories section or we have to provide with mockups.
Secondly, if this is final mock layout I can help with creating this layout.

**Comment by jhaanuj2108** [comment]
Hi @nishank95, these are not the final mocks. After submission of several mocks we mods and co-mods will select the one which is best and then the basic activities will be created after that contribution will start. Thanks. :)

**Comment by nishank95** [comment]
Hey, Check the UI from my side for the story section of GIS app. I am ready to contribute to any part/page of UI in this project 

<img src="https://user-images.githubusercontent.com/25129671/38744571-c6527070-3f5f-11e8-8c39-892c62139e4b.PNG" width="300">

**Comment by jhaanuj2108** [comment]
@nishank95 This mock is really great. Thanks for showing your interest. :blush:

**Comment by derrickabreo** [comment]
![read_story](https://user-images.githubusercontent.com/20537520/38764910-97c3ce54-3fd5-11e8-9c7f-400aa53a721d.png)

**Comment by amarjeetkapoor1** [comment]
Can we finalize these mockups?

**Comment by Saurav2304** [comment]
Yes..

**Comment by surya07081995** [comment]
Hi all,
Do Consider if it looks good to you!

<img src="https://user-images.githubusercontent.com/20954321/38783117-92521d62-411b-11e8-85ff-0b1ff9edbd0e.png"  height="500" width="250">
Thanks
