### ISSUE TITLE
White status bar on newly created Activities

### ISSUE THREAD

**Issue by YuganshT79** [UdacityAndroidDevScholarship/gis-2k18#81]
There is a white statusbar on every newly created Activity which does not look nice

![1](https://user-images.githubusercontent.com/12748767/39654767-e3bd0b10-5013-11e8-97cf-a36180aea17e.jpeg)
![2](https://user-images.githubusercontent.com/12748767/39654769-e76c3ff6-5013-11e8-8f98-f968414432dd.jpeg)

Also, the FAB in Projects fragment is having weird shadow

![3](https://user-images.githubusercontent.com/12748767/39654779-f58dd39c-5013-11e8-87ee-c26bf36fb6ed.jpeg)

**Comment by YuganshT79** [comment]
I am currently working on this issue

**Comment by TheRaider** [comment]
@YuganshT79 It was caused due to this attribute in values-v21
name="android:statusBarColor" -> @android:color/transparent
Just deleting this item will solve the issue.
