### ISSUE TITLE
Duplicate entries in app level gradle dependencies 

### ISSUE THREAD

**Issue by omi90** [UdacityAndroidDevScholarship/gis-2k18#87]
There are 4 duplicate entries in app level gradle dependencies.

    implementation 'com.google.firebase:firebase-core:12.0.1'
    implementation 'com.google.android.gms:play-services-auth:12.0.1'
    implementation 'com.google.firebase:firebase-auth:12.0.1'
    implementation 'com.google.firebase:firebase-core:12.0.1'

Same was causing error in some import statements in LoginActivity file

**Comment by TheRaider** [comment]
Solved by @sud8443  #88
